import "./globals.css";
import { Inter, Lexend } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const lexend = Lexend({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lexend.className}>{children}</body>
    </html>
  );
}
